# Generated by Django 4.2.16 on 2024-11-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
